### ISSUE TITLE
Handling authentication to a KCL module dependency on GitHub

### ISSUE THREAD

**Issue by maulik13** [vfarcic/crossplane-sql#88]
Hi Viktor! A big fan of your videos and it was great meeting you at Cloud Native Day in Bergen and chat about KCL. 

I am wondering how you are handling the dependency inside your KCLRun/KCLInput configuration using GitHub. How do you handle authentication to download dependency from GitHub at https://github.com/vfarcic/crossplane-sql/blob/main/kcl/aws.k#L1

I see that you had opened an issue in the function-kcl repo,  https://github.com/crossplane-contrib/function-kcl/issues/215

Feel free to close this if that ticket is exactly what my question is about.

**Comment by vfarcic** [comment]
I was not aware that KCL itself (nothing for do specifically with Crossplane KCL function) can pull models from different sources. I'm pulling schemas generated with Upbound from one of my Git repos. You can see an example at https://github.com/vfarcic/crossplane-sql/blob/8a23884369943525b66a2f16cebf090c470593b8/kcl/compositions.k#L36. That's similar to what Upbound is auto-generating when you build a Configuration OCI image that contains everything. In my case, that did not work since I needed something faster to keep running tests continuously while developing. That's why I "circumvented" Upbound packaging and went for the solution from the link above.

Please let me know if that's what you were looking for.

**Comment by maulik13** [comment]
Ah right! You are using KCL’s own ability to import and not relying on function-kcl?

So KCL in this case (and not the function-kcl) would just pull the KCL module from the specified Git repo in your linked config. But how do you get authentication to work? Just provide credential block with values or environment variables (ref:  https://github.com/kcl-lang/krm-kcl/blob/d19dfd727030092ca72601b442be31e6e73b6fec/README.md?plain=1#L83)

I will try this out tomorrow myself. I was stuck on looking at kcl function issue related to import.

**Comment by vfarcic** [comment]
I know that authentication works, but I haven't used it myself since, for now, all my Compositions where I used it are public and, even when they're not, schemas I'm using do not have anything confidential in them.

**Comment by maulik13** [comment]
Do you know what would be the best approach to get those credentials for a private git repository inside the composition. One option could be to use DeploymentRuntimeConfig to update the template and inject environment variables from a secret. But, I am wondering if that is the only option.

**Comment by maulik13** [comment]
FYI @vfarcic  we managed to solve this using the following config for functions-kcl

```yaml
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: fn-kcl
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          volumes:
            # Shared volume for the git configuration file
            - name: git-config
              emptyDir: {}
          initContainers:
            - name: init-gitconfig
              image: alpine:3.16
              volumeMounts:
                - name: git-config
                  mountPath: /config
              command:
                - /bin/sh
                - -c
                - |
                  # Write the git configuration file with the desired content.
                  # The file is created at /config/gitconfig so that the main container can use it.
                  mkdir /config/git
                  cat <<EOF > /config/git/config
                  [credential "https://github.com"]
                    username = infra-bot
                    helper = "!f() { test \"\$1\" = get && echo \"password=\${GITHUB_TOKEN}\"; }; f"
                  EOF
          containers:
            - name: package-runtime
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: gitsecret
                      key: password
              volumeMounts:
                - name: git-config
                  mountPath: /.config

```
